Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_download_options = {"limit-rate": "10240K"}
  config.vm.hostname = "jammy"
  config.vm.provision "ansible", playbook: "ansible-redmine.yml"
  config.vm.network "private_network", ip: "192.168.56.100"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
end
